version: '3.7'

services:
  db:
    image: postgres:12.6
    volumes:
      - ~/chat-docker/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data:
